CIRCUITPY_WIFI_SSID = "SSID"
CIRCUITPY_WIFI_PASSWORD = "PSSWD"
CIRCUITPY_WEB_INSTANCE_NAME = "EnvMon"
CIRCUITPY_WEB_API_PASSWORD="passw0rd"
CIRCUITPY_WEB_API_PORT=93
serial = 1
station = "kbos"
co2eq_base = 0x2e6
tvoc_base = 0xfe26

