CIRCUITPY_WIFI_SSID = "BudSpencer"
CIRCUITPY_WIFI_PASSWORD = "Pennstate123"
CIRCUITPY_WEB_INSTANCE_NAME = "GarageOpener"
CIRCUITPY_WEB_API_PASSWORD="passw0rd"
CIRCUITPY_WEB_API_PORT=204
triggerDistance = 20
